# Generated by Django 3.2.16 on 2024-05-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20240501_1231'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientcount',
            constraint=models.UniqueConstraint(fields=('ingredient', 'amount'), name='ingred-amount'),
        ),
    ]
