# Generated by Django 3.2.16 on 2024-05-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20240502_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientmesurment',
            old_name='measurment_unit',
            new_name='measurement_unit',
        ),
    ]
