# Generated by Django 5.0.4 on 2024-05-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_rename_measurment_unit_ingredientmesurment_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Цвет'),
        ),
    ]
