# Generated by Django 3.2.16 on 2024-05-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240501_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermain',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Пароль'),
        ),
    ]
